[api_config]
instance = "lemmy.ml"       # instance address here
listing_type = "Local"      # listing types: Local or All
sort_type = "Active"        # sorting types: New, Active, Hot, TopDay, TopHour, NewComments, Scaled, Controversial

[app_config]
title_len_chars = 27      #27
refresh_tick_sec = 60     #60
